name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
[env.production]
kv_namespaces = [{binding="KV_STATUS_PAGE", id="b410650562a044bebb0ae3fea109d582", preview_id=""}]
#zone_id="xxx"
#route="xxx"
